# Generated by Django 5.0.4 on 2024-04-14 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_user_is_email_confirmed_emailconfirmationtoken"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_email_confirmed",
            new_name="is_active",
        ),
    ]
