# Generated by Django 5.0.4 on 2024-04-21 17:08

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_onetimepassword_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="code",
            field=models.CharField(default="A1A82E", max_length=6),
        ),
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_at",
            field=models.DateTimeField(default=api.models.five_minutes),
        ),
    ]
