# Generated by Django 5.0.4 on 2024-04-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_onetimepassword_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="code",
            field=models.CharField(default="6D1B2A", max_length=6),
        ),
    ]
